# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85228807c8df105bf35c2ca668d06fb12412c5961f9e701306ceeb39867c0adc8340b62f4703ee0042f65ab146af6ca8da677787f53d1c478ffa0893adb9d2be

test:
  secret_key_base: dccfaed2b878e024e0b9281730d4864aee5dd82a2d04b90932d459ce02b014a29558d40cff4dcce140c6da0359dd1bbbc93dd1cff99086895874f786e92616c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
